services:
  # PostgreSQL Database Service
  db:
    image: dhi.io/postgres:17-debian13
    container_name: upquit-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: upquit_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis Cache Service
  redis:
    image: dhi.io/redis:8-debian13
    container_name: upquit-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  # Node.js Backend Service
  backend:
    image: dhi.io/node:24-debian13
    container_name: upquit-backend
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    command: node -e "setInterval(() => {}, 86400000)"

volumes:
  pgdata:
  redisdata:
